
# File: .github/workflows/workflow.yml

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Azure credentials
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Get secrets from Azure Key Vault
      id: keyvault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "kvvirtualteacher"
        secrets: 'subscription-id' # comma separated list of secret keys that need to be fetched from the Key Vault 

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./deploy

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ./deploy

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CREDENTIALS.clientId }}
        tenant-id: ${{ secrets.AZURE_CREDENTIALS.tenantId }}
        subscription-id: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'virtual-teacher-webapp-wus'
        slot-name: 'Production'
        package: .